name: 'stale-toggles'
description: 'Flag stale optimizely toggles'
author: 'Drew Wyatt <drew.j.wyatt@gmail.com>'
inputs:
  project:
    required: true
    description: 'optimizely project id'
  token:
    required: true
    description: 'optimizely personal access token'
runs:
  using: 'node12'
  main: 'dist/index.js'
